import trimesh
import numpy as np
import os

# --- 1. Define Component Dimensions (The Component Library) ---
# Unit: Meters
COLUMN_SIZE = [0.6, 0.6, 3.5]  # Width, Depth, Height
BEAM_SECTION = [0.4, 0.6]      # Width, Depth
GRID_SPACING = 6.0             # Center-to-center spacing

def create_column(x, y, z_bottom):
    """
    Generates a column at the specified (x, y) position.
    """
    # Create a Box primitive
    col = trimesh.creation.box(extents=COLUMN_SIZE)
    
    # Trimesh defaults the center to (0,0,0). We need to move it to the correct position.
    # Z-axis shift: Align bottom of column to z_bottom
    # XY-axis shift: Align center to grid intersection
    col.apply_translation([x, y, z_bottom + COLUMN_SIZE[2]/2])
    
    # Set color (Concrete Grey)
    col.visual.face_colors = [128, 128, 128, 255] 
    return col

def create_beam(x1, y1, x2, y2, z_height):
    """
    Generates a beam between two columns (automatically subtracts column width!).
    """
    # 1. Calculate vector and distance between two columns
    p1 = np.array([x1, y1])
    p2 = np.array([x2, y2])
    full_dist = np.linalg.norm(p2 - p1) # Should be 6.0m
    
    # 2. Calculate the "Net Length" of the beam
    # Subtract half the column width from both sides (0.3 + 0.3 = 0.6)
    # beam_len = 6.0 - 0.6 = 5.4m
    col_width = COLUMN_SIZE[0]
    beam_len = full_dist - col_width
    
    # 3. Create beam geometry
    # Dimensions: [Width, Depth, Length] -> Create along Z-axis first for easier rotation
    beam_size = [BEAM_SECTION[0], BEAM_SECTION[1], beam_len]
    beam = trimesh.creation.box(extents=beam_size)
    
    # 4. Rotate the beam (Lay the vertical beam flat)
    # This involves rotation matrices; trimesh handles alignment.
    # Default box is axis-aligned. Calculating rotation (Simplified for X-axis beam here).
    
    # Simplified: Assuming X-axis beam (from 0,0 to 6,0)
    # Rotate the Z-axis box to the X-axis
    # Rotate 90 degrees (pi/2) around Y-axis
    rot_matrix = trimesh.transformations.rotation_matrix(np.pi/2, [0, 1, 0])
    beam.apply_transform(rot_matrix)
    
    # 5. Move to correct position (Sit on top of columns)
    # X Center: Midpoint between columns
    # Z Height: Column Height - Beam Depth/2 (Flush with column top)
    mid_x = (x1 + x2) / 2
    mid_y = (y1 + y2) / 2
    top_z = z_height - BEAM_SECTION[1]/2
    
    beam.apply_translation([mid_x, mid_y, top_z])
    
    # Set color (Dark Grey)
    beam.visual.face_colors = [100, 100, 100, 255]
    return beam

def main():
    # --- 2. Assemble like an Architect ---
    scene_meshes = []
    
    print("🏗️ Generating Structure...")
    
    # Step A: Create two columns (Grid: 0,0 and 6,0)
    col1 = create_column(0, 0, 0)
    col2 = create_column(GRID_SPACING, 0, 0)
    scene_meshes.append(col1)
    scene_meshes.append(col2)
    print(f"✅ Created 2 Columns at (0,0) and ({GRID_SPACING},0)")
    
    # Step B: Create the connecting beam (Auto-calc 5.4m)
    beam = create_beam(0, 0, GRID_SPACING, 0, COLUMN_SIZE[2])
    scene_meshes.append(beam)
    print(f"✅ Created Beam connecting them (Length: {beam.bounds[1][0] - beam.bounds[0][0]:.2f}m)")
    
    # --- 3. Export Model ---
    # Merge all parts into a single scene
    scene = trimesh.Scene(scene_meshes)
    
    # Create output directory
    output_dir = "data/raw_sketchup" # Reusing this folder name, even though generated by Python
    os.makedirs(output_dir, exist_ok=True)
    
    output_path = os.path.join(output_dir, "task02_structure.obj")
    scene.export(output_path)
    print(f"🎉 Scene exported to: {output_path}")

if __name__ == "__main__":
    main()